---
- hosts: webservers
  remote_user: root
  roles:
    - webserver

  vars_prompt:
    - name: "stage"
      prompt: "Which stage to deploy ? (prod|staging)"
      private: no
    - name: "parameters_file_path"
      prompt: "Path of your parameters.yml file ?"
      private: no
    - name: "megasearch_similar_url_file_path"
      prompt: "Path of your megasearch_similar_url.txt file ?"
      private: no