---
- include: structure.yml
- include: deploy.yml

- include: permissions.yml
- include: bootstrap.yml
- include: permissions.yml


# Symlink shared files
- name: Delete release files to replace them by shared files
  file:
    state: absent
    path: "{{ deploy_to }}/releases/{{ timestamp.stdout }}/{{ item }}"
  with_items: linked_files

- name: Symlink of shared files
  file:
    state: link
    src: "{{ deploy_to_root }}/shared/{{ item }}"
    dest: "{{ deploy_to }}/releases/{{ timestamp.stdout }}/{{ item }}"
  with_items: linked_files


# Symlink of the release
- name: Create current symlink
  file:
    state: link
    src: "{{ deploy_to }}/releases/{{ timestamp.stdout }}"
    dest: "{{ deploy_to }}/current"


- name: Clean releases
  when: keep_releases > 0
  shell: cd {{ deploy_to }}/releases && ls -1r | tail -n +$(({{ keep_releases }} + 1)) | xargs rm -rf