---
- include: structure.yml
- include: deploy.yml

- include: permissions.yml
- include: bootstrap.yml
- include: permissions.yml

- include: symlink_shared_files.yml
- include: release.yml


- include: rollback.yml
  tags:
    - rollback
