---
# Application shared files
- stat: path={{ deploy_to_root }}/shared/app/config/parameters.yml
  register: parameters_yml
- stat: path={{ deploy_to_root }}/shared/web/megasearch_similar_url.txt
  register: megasearch_similar_url_txt
- stat: path={{ parameters_file_path_input }}
  register: parameters_yml_old
- stat: path={{ megasearch_similar_url_file_path_input }}
  register: megasearch_similar_url_txt_old

# Init : Input errors => abort playbook
- when: parameters_file_path_input != "" and parameters_yml_old.stat.exists == false
  fail: msg="This parameters.yml file does not exist !"
- when: parameters_file_path_input == "" and parameters_yml.stat.exists == false
  fail: msg="There is no current parameters.yml file at all. You must specify one !"
- when: megasearch_similar_url_file_path_input != "" and megasearch_similar_url_txt_old.stat.exists == false
  fail: msg="This megasearch_similar_url.txt file does not exist !"
- when: megasearch_similar_url_file_path_input == "" and megasearch_similar_url_txt.stat.exists == false
  fail: msg="There is no current megasearch_similar_url.txt file at all. You must specify one !"


- name: Create shared directory
  file: >
    state=directory
    owner=root group=root
    path={{ deploy_to_root }}/shared
- name: Create logs directory
  file: >
    state=directory
    owner=root group=root
    path={{ deploy_to }}/logs

# Copy shared files from existing source if they dont already exist
- name: Add parameters.yml in shared directory
  shell: mkdir -p {{ deploy_to_root }}/shared/app/config && cp {{ parameters_file_path_input }} {{ deploy_to_root }}/shared/app/config
  when: parameters_yml.stat.exists == false
- name: Add megasearch_similar_url.txt in shared directory
  shell: mkdir -p {{ deploy_to_root }}/shared/web && cp {{ megasearch_similar_url_file_path_input }} {{ deploy_to_root }}/shared/web
  when: megasearch_similar_url_txt.stat.exists == false


- debug: msg="Files structure verified. Everything is OK !"
- pause: